server:
  port: 8081

spring:
  application:
    name: dou-server

  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dou?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai


aliyun:
  sls:
    access-key-id: xxx
    access-key-secret: xxx
    logstore: prod
